const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
const REMOVE_FAV = 'REMOVE_FAV';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const ADD_WISHLIST = 'ADD_WISHLIST';
const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';

export {
  FETCH_PRODUCTS_ERROR,
  FETCH_PRODUCTS_PENDING,
  FETCH_SINGLE_SUCCESS,
  FETCH_PRODUCTS_SUCCESS,
  CREATE_ITEM_PENDING,
  REMOVE_FAV,
  ADD_WISHLIST,
  FETCH_SINGLE_PENDING,
};
