// Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const GET_USER = 'GET_USER';
export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
export const REMOVE_FAV = 'REMOVE_FAV';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
